# Generated by Django 3.2.3 on 2022-04-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
